---
- name: Install packets
  package: name={{ item }} state=present
  with_items:
    - sssd-ldap

# Name Service Switch aggregiert verschiedene Datenquellen (LDAP, /etc/passwd)
- name: setup nsswitch.conf
  template:
    src: nsswitch.conf.j2
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
- name: setup sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: restart sssd
- name: setup openldap
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
    owner: root
    group: root
    mode: 0644
- name: Install ldap-certs
  copy:
    src: "{{cert_src}}"
    dest: "{{cert_dest}}"
    owner: root
    group: root
    mode: 0644
- name: Allow ldap-users to login..
  pamd:
    name: "{{item}}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    state: before
    new_type: auth
    new_control: sufficient
    new_module_path: pam_sss.so
    module_arguments: forward_pass
  with_items: "{{ pam_services }}"
- name: part2
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_unix.so
    state: before
    new_type: account
    new_control: "[default=bad success=ok user_unknown=ignore authinfo_unavail=ignore]"
    new_module_path: pam_sss.so
  with_items: "{{ pam_services }}"
- name: part3
  pamd:
    name: "{{ item }}"
    type: session
    control: required
    module_path: pam_unix.so
    state: before
    new_type: session
    new_control: optional
    new_module_path: pam_sss.so
  with_items: "{{ pam_services }}"
